version: '3'
services:
  web:
    build: ./web
    ports:
      - "8000:8000"
    links:
      - postgres:postgres
    env_file: .env
    volumes:
      - ./web:/usr/src/app
    depends_on:
     - postgres
    command: bash -c "python /usr/src/app/create_db.py && /usr/local/bin/gunicorn -w 2 -b :8000 app:app"

  postgres:
    image: postgres:12.2
    ports:
      - "5432:5432"
    environment:
      TZ: "Australia/Melbourne"
      #  these are our database credentials.
      #  for the purposes of this workshop, this is not relevant and shouldn't be changed.
      #  it is just here as we are staging the database via docker.
      #  in a prod environment this would be done differently (or not in Docker at all).
      #  🌌 these aren't the droids you are looking for 🌌
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
