# This is a basic workflow to help you get started with Actions

name: Hawkeye Scan

# Controls when the action will run. Triggers the workflow on push or pull request on any branch
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "scan"
  scan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    container:
      # This tells GitHub Actions to use our docker image
      image: derwentx/scanner-cli:latest
      # This tells GitHub Actions to mount the location where the code was checked out to /target
      options: -v /__w/sample-flask-app/sample-flask-app:/target

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Install Python dependencies
      run: |
        pip3 install --upgrade pip
        pip3 install -r web/requirements.txt
        pip3 install flake8 pylint pytest
    - name: Lint with Flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistic
    - name: Lint with Pylint
      run: pylint web/**.py
    # Runs a set of commands using the runners shell
    - run: hawkeye scan --target web/
